### ISSUE TITLE
The SCM resources are not getting detected when the multibranch pipeline is inside a folder

### ISSUE THREAD

**Issue by madhuhaasnannaka** [jenkinsci/synopsys-security-scan-plugin#194]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
![Image](https://github.com/user-attachments/assets/2795675d-35d4-4a94-b224-940dd04020e6)
The above image shows the PLugin can detect the SCM resources like repo name, BitBucket username, etc.

But when the job is inside a folder in Jenkins  It can't see the SCM resources set like in here![Image](https://github.com/user-attachments/assets/180906f1-647a-4357-8aaf-7b41f788d4d5)



  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

I am running the build on the K8s Linux pod created by the k8s plugin. 

### Reproduction steps

1. Set the SCM resources
2. try running the PR job inside a folder, where we can see that it won't see the SCM resources.
3. But unlike a folder, if the job runs without a folder, it can see SCM resources.

### Expected Results

We should be able to see the SCM resources getting detected without a folder or inside a folder in Jenkins. 

### Actual Results

SCM resources are not getting detected when the Jos is running  inside a folder in Jenkins

**Comment by jahid1209** [comment]
@madhuhaasnannaka 

This issue has been resolved in the [rebranded plugin](https://github.com/jenkinsci/blackduck-security-scan-plugin). Additionally, **this plugin will be deprecated very soon**. 

Please use the [Blackduck Security Scan](https://plugins.jenkins.io/blackduck-security-scan/) (**version 2.0.1**). [Blackduck Security Scan Plugin](https://plugins.jenkins.io/blackduck-security-scan/) is the rebranded product of the [Synopsys Security Scan](https://plugins.jenkins.io/synopsys-security-scan/) plugin.
 
Official documentation can be found [here](https://documentation.blackduck.com/bundle/bridge/page/documentation/get_started_with_security_scan_for_jenkins.html). Migration guide can be found [here](https://community.blackduck.com/s/article/integrations-black-duck-migration-instructions).

Thanks!

**Comment by madhuhaasnannaka** [comment]
@jahid1209 Thanks for the update and the Information.
